### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by arenzana** [ChubbsSolutions/lottoman#1]
Your documentation sucks.

**Comment by barneshere** [comment]
Thanks for you interest in this important project.   Your concerns have
been considered and we are diligently working on a resolution.

**Comment by barneshere** [comment]
Kind Sir,   

Our outstanding team has provided an update to address your concerns.

Hope they meet your satisfaction.

**Comment by arenzana** [comment]
The Documentation is wonderful now. Thanks!
